controllers:
    resource:
        path: ../src/Controller
        namespace: App\Controller
    type: attribute

app_ui_controllers:
    resource: 
        path: ../src/UI/Controller/
        namespace: App\UI\Controller
    type: attribute
    prefix: /
